# Generated by Django 4.2.30 on 2026-04-26 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='new_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='previous_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
