# Generated by Django 4.2.30 on 2026-04-26 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_alter_product_slug'),
        ('ecommerce', '0003_order_customer_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.product'),
        ),
    ]
